create proc get_foreign_tables(@p_t_name nvarchar(100)) as

	select
		sys.tables.[name]
	from
		INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
	left join INFORMATION_SCHEMA.TABLE_CONSTRAINTS on INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.CONSTRAINT_NAME
	left join sys.foreign_keys on sys.foreign_keys.[name] = INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME
	left join sys.tables on sys.tables.[object_id] = sys.foreign_keys.parent_object_id
	left join INFORMATION_SCHEMA.COLUMNS on INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME
	where
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS.TABLE_NAME = @p_t_name