create proc get_foreign_columns @t_name nvarchar(100) as

	select
		INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME,
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME,
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE.COLUMN_NAME
	from
		sys.tables
	left join sys.foreign_keys on sys.foreign_keys.parent_object_id = sys.tables.[object_id]
	left join INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS on INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = sys.foreign_keys.[name]
	left join INFORMATION_SCHEMA.KEY_COLUMN_USAGE on INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_NAME
	left join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE on INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.CONSTRAINT_NAME = INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME
	where
		sys.tables.[name] = @t_name